# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}

package:
  name: rapids-dask-dependency
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask ==2024.1.1
    - dask-core ==2024.1.1
    - distributed ==2024.1.1
    - dask_expr ==0.4.0

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_file: LICENSE
  summary: Standardized Dask dependency pinnings across RAPIDS
  description: |
    This metapackage encodes the standard Dask version pinning used for a
    particular release of RAPIDS. The metapackage adds an extra release segment
    to the RAPIDS CalVer to allow pinnings in this metapackage to be updated
    for a given release and automatically propagate to its dependents.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/rapids_dask_dependency

