# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: rapids-dask-dependency
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: ${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - setuptools
  run:
    - dask ==2025.2.0
    - dask-core ==2025.2.0
    - distributed ==2025.2.0

tests:
  - script:
      - python -m pytest -v tests/
    files:
      source:
        - tests/*
    requirements:
      run:
        - pytest

about:
  homepage: https://github.com/rapidsai/rapids-dask-dependency
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
