# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  datetime_string: '${{ env.get("RAPIDS_DATETIME_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: rapids-dask-dependency
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: ${{ datetime_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - setuptools>=77.0.0
  run:
    - bokeh <3.10
    # >=,< form is preferred here to allow for post-releases to fix packaging problems (e.g. 2026.3.0.post1)
    # or targeted releases to fix security issues (like 2026.3.0.1)
    - dask >=2026.7.1,<2026.7.2
    - dask-core >=2026.7.1,<2026.7.2
    - distributed >=2026.7.1,<2026.7.2

tests:
  - script:
      - python -m pytest -v tests/
    files:
      source:
        - tests/*
    requirements:
      run:
        - pytest

about:
  homepage: https://github.com/rapidsai/rapids-dask-dependency
  license: ${{ load_from_file("pyproject.toml").project.license }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
